export enum ServerEvent {
  JOINED = 'JOINED',
  TIME_REMAINING = 'TIME_REMAINING',
  HOVERED = 'HOVERED',
  PLAYER_CONNECTED_TO_MATCH = 'CONNECTED_TO_MATCH',
  DISCONNECTED_FROM_MATCH = 'DISCONNECTED_FROM_MATCH',
}
