export enum ServerEvent {
  JOINED = 'JOINED',
  MADE_MOVE = 'MADE_MOVE',
  TIME_REMAINING = 'TIME_REMAINING',
  HOVERED = 'HOVERED',
  PLAYER_CONNECTED_TO_MATCH = 'PLAYER_CONNECTED_TO_MATCH',
  DISCONNECTED_FROM_MATCH = 'DISCONNECTED_FROM_MATCH',
  UPDATED_GAME_SETTINGS = 'UPDATED_GAME_SETTINGS',
}
